language: c
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update -qq ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -qq libgtk2.0-dev libpoppler-glib-dev libcups2 ; fi
compiler:
  - clang
  - gcc
script:
  - ./configure --prefix="$HOME/build/jristz/"
  - make
  - make DESTDIR="$HOME/build/jristz/" install
